### ISSUE TITLE
Ingress is not working 

### ISSUE THREAD

**Issue by alan890104** [gamerslouis/cloudnative_helm_charts#7]
## Description
We want to access our services inside k8s via setting routes in ingress.
However, the config of my-ingress below cannot work:
```yaml
rules:
  - host: tsmc-group-1.com
    http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: tsmc-grafana
            port:
              name: http
```
